local path = minetest.get_modpath("techage_nuclear")
dofile(path.."/content/uranium.lua")
dofile(path.."/content/centrifuge.lua")
dofile(path.."/content/reactor.lua")
dofile(path.."/content/crafts.lua")
dofile(path.."/content/nodes.lua")
dofile(path.."/content/items.lua")
dofile(path.."/content/pipes.lua")
dofile(path.."/content/steam.lua")
